DROP TABLE IF EXISTS ai_memories CASCADE;
DROP TABLE IF EXISTS ai_game_stats CASCADE;
DROP TABLE IF EXISTS ai_traits CASCADE;
DROP TABLE IF EXISTS ai_game_history CASCADE;
DROP TABLE IF EXISTS ai_chat_messages CASCADE;
DROP TABLE IF EXISTS ai_users CASCADE;

DROP FUNCTION IF EXISTS ai_set_updated_at() CASCADE;
